name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # Matches stable releases (e.g., 25.2.2)
      - "[0-9]+.[0-9]+.[0-9]+-*" # Matches pre-release tags (e.g., 25.2.2-alpha.0, 25.2.2-beta.1)
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: "https://registry.npmjs.org/"
        always-auth: true

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile # Do not need a lock file for this library

    - name: Build library
      run: pnpm build

    - name: Publish to npm
      if: startsWith(github.ref, 'refs/tags/')  # Runs only when a tag is pushed
      run: |
        TAG_NAME=$(echo $GITHUB_REF | sed 's|refs/tags/||')

        if [[ $TAG_NAME == *"-alpha"* || $TAG_NAME == *"-beta"* || $TAG_NAME == *"-rc"* ]]; then
          echo "Publishing pre-release $TAG_NAME as PUBLIC with 'beta' tag"
          pnpm publish --tag beta --access public --no-git-checks
        else
          echo "Publishing stable version $TAG_NAME as PUBLIC with 'latest' tag"
          pnpm publish --tag latest --access public --no-git-checks
        fi
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
